// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYXRmEvuazaf8UY27NmHFpCsarKLMhVNo',
    appId: '1:757807835312:web:ee9e648ebdf936dd95b375',
    messagingSenderId: '757807835312',
    projectId: 'projet-40b07',
    authDomain: 'projet-40b07.firebaseapp.com',
    storageBucket: 'projet-40b07.firebasestorage.app',
    measurementId: 'G-NYTJZY4NLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIuERYkBvCvN9DhBOBTVMCWvrtWk4M2HM',
    appId: '1:757807835312:android:9c46f9b092795b7295b375',
    messagingSenderId: '757807835312',
    projectId: 'projet-40b07',
    storageBucket: 'projet-40b07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCshO_dhsTfA_vW6TsRprx_wiUPufrHAeY',
    appId: '1:757807835312:ios:a0acf1eefe70092495b375',
    messagingSenderId: '757807835312',
    projectId: 'projet-40b07',
    storageBucket: 'projet-40b07.firebasestorage.app',
    iosBundleId: 'com.example.loumiprojet11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqas0Tfi353GxyYaxK0tAYh7YaiImt4TM',
    appId: '1:647947439741:ios:0893543efbe407ef8a2b14',
    messagingSenderId: '647947439741',
    projectId: 'projetds-35f8a',
    storageBucket: 'projetds-35f8a.firebasestorage.app',
    iosBundleId: 'com.example.sapacetoon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYXRmEvuazaf8UY27NmHFpCsarKLMhVNo',
    appId: '1:757807835312:web:0f5dfece68850c6395b375',
    messagingSenderId: '757807835312',
    projectId: 'projet-40b07',
    authDomain: 'projet-40b07.firebaseapp.com',
    storageBucket: 'projet-40b07.firebasestorage.app',
    measurementId: 'G-R96BDGNC3G',
  );

}